server:
  port: 8083
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: goProvider
          uri: lb://consumer
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1